### ISSUE TITLE
DAAM not working at all + Error in saving single image among a batch

### ISSUE THREAD

**Issue by Sequentilian** [kousw/stable-diffusion-webui-daam#10]
Attempting to use the DAAM script doesn't seem to work at all. The image generates with no heatmap present, no matter what settings are altered.

Commandline arguments like --xformers and --no-half-vae do not affect DAAM. Was tested on SD 1.4 and Anything-V3.0, but _changing model does not seem to affect it either._

Running on an RTX 2060 using the aforementioned commandline args (no --medvram), automatic saving of images is turned off, and I have attempted to install it through the webui's installer, and then by installing it manually. Neither worked. Version of python is 3.10.6. Should it be just plain 3.10? I have done 'git pull' to ensure the webui is on the absolute latest version.

![image](https://user-images.githubusercontent.com/74772174/206825259-e1d86d1b-8def-4c84-a656-77c4da93574c.png)

If it's worth changing the settings, here is a screenshot of those in case anything is relevant.

![image](https://user-images.githubusercontent.com/74772174/206826591-28521317-8b85-4e01-a203-46fa2d579b4f.png)

Nothing in the console seems to be of interest when a single image is generated. Just the line "daam run with context_size= 154" before the generation progress.

When rendering _more than one image_, attempting to save any particular image of the batch results in the console error listed below. These problems may be related, so I am putting them together as one issue in case solving one solves the other.

Error message when saving one image of many:

Error completing request
Arguments: ('{"prompt": "masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo", "all_prompts": ["masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo", "masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo", "masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo", "masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo"], "negative_prompt": "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo", "all_negative_prompts": ["lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo", "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo", "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo", "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo"], "seed": 3533355142, "all_seeds": [3533355142, 3533355143, 3533355144, 3533355145], "subseed": -1, "all_subseeds": [2040153147, 2040153148, 2040153149, 2040153150], "subseed_strength": 0, "width": 512, "height": 512, "sampler_name": "Euler", "cfg_scale": 8, "steps": 28, "batch_size": 2, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "38c1ebe3", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": null, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["masterpiece, best quality, 1girl, all fours, huge ass, thick thighs, blonde hair, huge breasts, crop top, dark-skinned female, dark skin, gradient, gradient background, hanging breasts, high heels, long hair, no bra, rabbit ears, rabbit girl, rabbit tail, shirt, shorts, solo, tail, thighhighs, underboob, white legwear, solo\\nNegative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name, duo\\nSteps: 28, Sampler: Euler, CFG scale: 8, Seed: 3533355142, Size: 512x512, Model hash: 38c1ebe3, Batch size: 2, Batch pos: 0, Clip skip: 2"], "styles": ["None", "None"], "job_timestamp": "20221210125658", "clip_skip": 2, "is_using_inpainting_conditioning": false}', [{'name': 'C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmptk174m4v.png', 'data': 'file=C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmptk174m4v.png', 'is_file': True}, {'name': 'C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmp62lcwbcn.png', 'data': 'file=C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmp62lcwbcn.png', 'is_file': True}, {'name': 'C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmpnnl24r03.png', 'data': 'file=C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmpnnl24r03.png', 'is_file': True}, {'name': 'C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmpx30txq7c.png', 'data': 'file=C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmpx30txq7c.png', 'is_file': True}, {'name': 'C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmp9qangi_a.png', 'data': 'file=C:\\Users\\NAME\\AppData\\Local\\Temp\\tmpxiocxzuf\\tmp9qangi_a.png', 'is_file': True}], False, 4) {}
Traceback (most recent call last):
  File "C:\webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "C:\webui\modules\ui.py", line 135, in save_files
    fullfn, txt_fullfn = save_image(image, path, "", seed=p.all_seeds[i], prompt=p.all_prompts[i], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
IndexError: list index out of range

Traceback (most recent call last):
  File "C:\webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

**Comment by kousw** [comment]
You need to enable "Always save all generated images".
This script hooks the process of saving images.

**Comment by Sequentilian** [comment]
That seems to have worked, thank you! Just wondering, is it possible to generate the heatmap for images without saving all the generated images? I don't like my folder being filled by a bunch of generations I don't want to use. I understand if it isn't possible.

**Comment by kousw** [comment]
I have added a "Do not save heatmap images" option, although you still need to enable "Always save all generated images"

**Comment by stysmmaker** [comment]
Related to this — when trying to save an image manually using the "Save" button, a similar error occurs, this being the first part of the trackback (the second being the same):
```
Traceback (most recent call last):
  File "Q:\AI\git\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "Q:\AI\git\stable-diffusion-webui\modules\ui.py", line 136, in save_files
    fullfn, txt_fullfn = save_image(image, path, "", seed=p.all_seeds[i], prompt=p.all_prompts[i], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
IndexError: list index out of range
```
This happens regardless of the state of "Do not save heatmap images". Is this something that can be resolved or can it not due to how the script hooks into the image save process currently?

**Comment by kousw** [comment]
Trying to show them in the gallery of generated images seems to result in index errors. But I will at least try to be able to save the original images.

**Comment by kousw** [comment]
Fixed. You can now save.

**Comment by stysmmaker** [comment]
Works now, thanks!
