### ISSUE TITLE
Cannot load DAAM after  installation via webui extensions tab

### ISSUE THREAD

**Issue by PGadoury** [kousw/stable-diffusion-webui-daam#11]
Relevant error in terminal:

```
Error loading script: daam_script.py
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\modules\scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "D:\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 20, in <module>
    from scripts.daam import trace, utils
ModuleNotFoundError: No module named 'scripts.daam'
```

Looking around in file explorer, there does seem to be a scripts/daam directory

`D:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam`

**Comment by PGadoury** [comment]
Looking around the directory, there does seem to be a scripts/daam directory

D:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam

**Comment by Sequentilian** [comment]
This might be a stupid question, but have you updated your webui to the latest version?
If you have, I recommend deleting DAAM from extensions folder, restarting webui, and installing again.

**Comment by PGadoury** [comment]
Ok, after a few reinstalls, it seems it was a (user) error due to conda environment and webui using python 3.7.
Thanks for your help!

**Comment by Sequentilian** [comment]
What exact version of Python are you using now? Is it 3.10, or 3.10.6?

**Comment by PGadoury** [comment]
The script works as intended for me
